#!/bin/csh -f
##### 
##   Sung-Hoon Ko
##   7/2/98
#####


# Run synthetic test cases
 
set executableJAVA = PingPong
set executableC = mpi_single
           
 
set nprocs  = 2

set mpiJavaHome = ../..
set mpiJavaClasses = ../../lib/classes

set MPI       = mpich

set MPI_PATH  = /usr/local/mpich2
set JAVA_PATH = /usr/java/jdk1.5.0_14/

set CLASS_PATH = "-classpath .:${mpiJavaClasses}"
set JAVA_C = "${JAVA_PATH}/bin/javac ${CLASS_PATH}"


set CWD = `pwd`

        ## Benchmarking  MPI-C
        echo ...Running : {$CWD:t}/${executableC}.c
        $mpiJavaHome/src/scripts/prun ${nprocs[1]}  $executableC

        ## Benchmarking  MPI-JAVA
        endif   
        echo " "
        echo "**********************************************"
        echo " "
        echo ...Running : {$CWD:t}/${executableJAVA}.java
        $mpiJavaHome/src/scripts/prunjava ${nprocs[1]} $executableJAVA 

